pipeline {
    agent any
    
    tools {
        maven 'Maven' // Use the name of your Maven installation in Jenkins
    }

    stages {
        stage('Clean and Test') {
            steps {
                echo 'Building and Testing...'
                bat 'mvn clean test' // Using bat instead of sh for Windows
            }
        }
    }
    
    post {
        always {
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
        }
    }
}
