pipeline {
    agent any
    triggers {
        cron('24 14 * * *')   // Run January 12 at 14:00
    }
    tools {
        maven 'Maven' 
    }

    stages {
        stage('Clean and Test') {
            steps {
                echo 'Building and Testing...'
                bat 'mvn clean test -f testNgPractice/pom.xml'
            }
        }
    }
    
    post {
        always {
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
        }
    }
}
